"use client";
import { useEffect, useMemo, useState } from "react";
import { ClipboardList, Plus } from "lucide-react";

type Employee={id:number;employeeCode:string;firstName:string;lastName:string};
type Leave={id:number;employeeId:number;type:string;startDate:string;endDate:string;reason:string;status:string;employee:Employee};
const blank={employeeId:"",type:"CASUAL",startDate:"",endDate:"",reason:""};
export default function LeavesPage(){
  const [employees,setEmployees]=useState<Employee[]>([]);const [items,setItems]=useState<Leave[]>([]);const [filter,setFilter]=useState("ALL");const [show,setShow]=useState(false);const [form,setForm]=useState(blank);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  async function load(){const [e,l]=await Promise.all([fetch("/api/employees"),fetch("/api/leaves")]);setEmployees((await e.json()).employees??[]);setItems((await l.json()).requests??[])} useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>filter==="ALL"?items:items.filter(x=>x.status===filter),[items,filter]);
  async function create(ev:React.FormEvent){ev.preventDefault();setBusy(true);const r=await fetch("/api/leaves",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error??"Could not create request");return;}setShow(false);setForm(blank);setError("");load()}
  async function update(id:number,status:string){await fetch(`/api/leaves/${id}/status`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});load()}
  const counts={PENDING:items.filter(x=>x.status==="PENDING").length,APPROVED:items.filter(x=>x.status==="APPROVED").length,REJECTED:items.filter(x=>x.status==="REJECTED").length};
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-sm font-semibold text-indigo-600">Time off workflow</div><h1 className="mt-1 text-3xl font-black">Leave requests</h1><p className="mt-2 text-sm text-slate-500">Create requests and approve or reject them from one place.</p></div><button className="btn btn-primary" onClick={()=>setShow(true)}><Plus size={16}/> New request</button></div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">Pending</div><div className="mt-2 text-3xl font-black">{counts.PENDING}</div><div className="mt-1 text-xs text-slate-500">awaiting decision</div></div><div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">Approved</div><div className="mt-2 text-3xl font-black">{counts.APPROVED}</div><div className="mt-1 text-xs text-slate-500">approved requests</div></div><div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">Rejected</div><div className="mt-2 text-3xl font-black">{counts.REJECTED}</div><div className="mt-1 text-xs text-slate-500">rejected requests</div></div></div>
    <div className="card overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 p-4 sm:flex-row"><div className="flex gap-2">{["ALL","PENDING","APPROVED","REJECTED"].map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-xl px-3 py-2 text-xs font-bold ${filter===x?"bg-indigo-50 text-indigo-700":"text-slate-500 hover:bg-slate-50"}`}>{x}</button>)}</div><div className="text-xs text-slate-400">{filtered.length} request{filtered.length!==1?"s":""}</div></div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Dates</th><th className="px-5 py-3">Reason</th><th className="px-5 py-3">Status / Action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(l=><tr key={l.id}><td className="px-5 py-4"><div className="text-sm font-bold">{l.employee.firstName} {l.employee.lastName}</div><div className="text-xs text-slate-500">{l.employee.employeeCode}</div></td><td className="px-5 py-4 text-sm text-slate-600">{l.type}</td><td className="px-5 py-4 text-sm text-slate-600">{new Date(l.startDate).toLocaleDateString("en-IN",{day:"2-digit",month:"short"})} – {new Date(l.endDate).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</td><td className="max-w-xs px-5 py-4 text-sm text-slate-600">{l.reason}</td><td className="px-5 py-4"><div className="flex flex-wrap items-center gap-2"><span className={`badge ${l.status==="PENDING"?"bg-amber-50 text-amber-700":l.status==="APPROVED"?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700"}`}>{l.status}</span>{l.status==="PENDING"&&<><button className="btn btn-secondary px-3 py-1.5 text-xs" onClick={()=>update(l.id,"APPROVED")}>Approve</button><button className="btn btn-danger px-3 py-1.5 text-xs" onClick={()=>update(l.id,"REJECTED")}>Reject</button></>}</div></td></tr>)}{filtered.length===0&&<tr><td colSpan={5} className="px-5 py-14 text-center"><ClipboardList className="mx-auto text-slate-300"/><div className="mt-3 text-sm font-semibold">No requests in this filter</div></td></tr>}</tbody></table></div></div>
    {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div><h2 className="text-xl font-black">New leave request</h2><p className="mt-1 text-xs text-slate-500">This demo creates a request in Pending status.</p></div><form className="mt-6 space-y-4" onSubmit={create}><div><label className="label">Employee</label><select className="input" required value={form.employeeId} onChange={e=>setForm({...form,employeeId:e.target.value})}><option value="">Select employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.firstName} {e.lastName} ({e.employeeCode})</option>)}</select></div><div><label className="label">Leave type</label><select className="input" value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>CASUAL</option><option>SICK</option><option>EARNED</option><option>OTHER</option></select></div><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Start date</label><input className="input" type="date" required value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></div><div><label className="label">End date</label><input className="input" type="date" required value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})}/></div></div><div><label className="label">Reason</label><textarea className="input min-h-24" required value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div>{error&&<div className="rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{error}</div>}<div className="flex justify-end gap-2"><button type="button" className="btn btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn btn-primary" disabled={busy}>{busy?"Creating...":"Create request"}</button></div></form></div></div>}
  </div>
}
