"use client";
import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Trash2, Users } from "lucide-react";

type Employee = { id:number; employeeCode:string; firstName:string; lastName:string; email:string; phone:string|null; department:string; designation:string; joinDate:string; status:string; salary:number|null };
const emptyForm = { employeeCode:"", firstName:"", lastName:"", email:"", phone:"", department:"Engineering", designation:"", joinDate:"", salary:"" };
const departments = ["Engineering","Human Resources","Design","Finance","Sales","Operations"];

export default function EmployeesPage() {
  const [items,setItems]=useState<Employee[]>([]); const [q,setQ]=useState(""); const [show,setShow]=useState(false); const [editId,setEditId]=useState<number|null>(null); const [form,setForm]=useState(emptyForm); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function load(){ const r=await fetch("/api/employees"); const d=await r.json(); setItems(d.employees??[]); }
  useEffect(()=>{load()},[]);
  const filtered=useMemo(()=>items.filter(e=>`${e.firstName} ${e.lastName} ${e.employeeCode} ${e.department} ${e.designation}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
  function openAdd(){setEditId(null);setForm(emptyForm);setError("");setShow(true)}
  function openEdit(e:Employee){setEditId(e.id);setForm({employeeCode:e.employeeCode,firstName:e.firstName,lastName:e.lastName,email:e.email,phone:e.phone??"",department:e.department,designation:e.designation,joinDate:e.joinDate.slice(0,10),salary:e.salary?String(e.salary):""});setError("");setShow(true)}
  async function save(ev:React.FormEvent){ev.preventDefault();setBusy(true);setError(""); const url=editId?`/api/employees/${editId}`:"/api/employees"; const r=await fetch(url,{method:editId?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,salary:form.salary?Number(form.salary):null})}); const d=await r.json();setBusy(false);if(!r.ok){setError(d.error??"Could not save employee");return;}setShow(false);load();}
  async function remove(id:number){if(!window.confirm("Delete this employee? Their attendance and leave records will also be removed.")) return;await fetch(`/api/employees/${id}`,{method:"DELETE"});load();}
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-sm font-semibold text-indigo-600">People directory</div><h1 className="mt-1 text-3xl font-black">Employees</h1><p className="mt-2 text-sm text-slate-500">Create, edit and manage employee records.</p></div><button className="btn btn-primary" onClick={openAdd}><Plus size={16}/> Add employee</button></div>
    <div className="card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row"><div className="flex flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3"><Search size={16} className="text-slate-400"/><input className="w-full py-2.5 text-sm outline-none" placeholder="Search name, ID, department..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="rounded-xl bg-slate-50 px-4 py-2.5 text-sm font-semibold text-slate-600">{filtered.length} employees</div></div>
      <div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Department</th><th className="px-5 py-3">Role</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map(e=><tr key={e.id} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-indigo-50 text-xs font-bold text-indigo-700">{e.firstName[0]}{e.lastName[0]}</div><div><div className="text-sm font-bold">{e.firstName} {e.lastName}</div><div className="text-xs text-slate-500">{e.employeeCode} · {e.email}</div></div></div></td><td className="px-5 py-4 text-sm text-slate-600">{e.department}</td><td className="px-5 py-4 text-sm text-slate-600">{e.designation}</td><td className="px-5 py-4"><span className={`badge ${e.status==="ACTIVE"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{e.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button className="rounded-lg p-2 text-slate-500 hover:bg-slate-100 hover:text-slate-900" onClick={()=>openEdit(e)}><Pencil size={15}/></button><button className="rounded-lg p-2 text-rose-500 hover:bg-rose-50" onClick={()=>remove(e.id)}><Trash2 size={15}/></button></div></td></tr>)}{filtered.length===0&&<tr><td colSpan={5} className="px-5 py-14 text-center"><Users className="mx-auto text-slate-300"/><div className="mt-3 text-sm font-semibold">No employees found</div><div className="mt-1 text-xs text-slate-400">Try another search or add a new employee.</div></td></tr>}</tbody></table></div>
    </div>
    {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/40 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-black">{editId?"Edit employee":"Add employee"}</h2><p className="mt-1 text-xs text-slate-500">Only the fields needed for this HRMS are included.</p></div><button className="rounded-lg px-2 py-1 text-slate-400 hover:bg-slate-100" onClick={()=>setShow(false)}>✕</button></div><form onSubmit={save} className="mt-6 grid gap-4 sm:grid-cols-2"><div><label className="label">Employee ID</label><input className="input" required value={form.employeeCode} onChange={e=>setForm({...form,employeeCode:e.target.value})}/></div><div><label className="label">Join date</label><input className="input" type="date" required value={form.joinDate} onChange={e=>setForm({...form,joinDate:e.target.value})}/></div><div><label className="label">First name</label><input className="input" required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></div><div><label className="label">Last name</label><input className="input" required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></div><div><label className="label">Email</label><input className="input" required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><label className="label">Phone</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Department</label><select className="input" value={form.department} onChange={e=>setForm({...form,department:e.target.value})}>{departments.map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Designation</label><input className="input" required value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></div><div><label className="label">Annual salary (₹)</label><input className="input" type="number" min="0" value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})}/></div>{error&&<div className="sm:col-span-2 rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700">{error}</div>}<div className="mt-2 flex justify-end gap-2 sm:col-span-2"><button type="button" className="btn btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?"Saving...":editId?"Save changes":"Create employee"}</button></div></form></div></div>}
  </div>
}
