"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarCheck2, Check, Clock3 } from "lucide-react";

type Employee={id:number;employeeCode:string;firstName:string;lastName:string;department:string};
type Record={employeeId:number;status:string;checkIn:string|null;checkOut:string|null};
const statuses=["PRESENT","ABSENT","HALF_DAY","WORK_FROM_HOME"];
function keyDate(){const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
export default function AttendancePage(){
  const [employees,setEmployees]=useState<Employee[]>([]); const [records,setRecords]=useState<Record[]>([]); const [date,setDate]=useState(keyDate()); const [busy,setBusy]=useState<number|null>(null); const [message,setMessage]=useState("");
  async function load(){const [e,r]=await Promise.all([fetch("/api/employees"),fetch(`/api/attendance?date=${date}`)]);const ed=await e.json(),rd=await r.json();setEmployees(ed.employees??[]);setRecords((rd.records??[]).map((x: any)=>({employeeId:x.employeeId,status:x.status,checkIn:x.checkIn,checkOut:x.checkOut})))}
  useEffect(()=>{load()},[date]);
  const map=useMemo(()=>new Map(records.map(r=>[r.employeeId,r])),[records]);
  async function save(employeeId:number,status:string){setBusy(employeeId);setMessage("");const now=new Date();const r=await fetch("/api/attendance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({employeeId,date,status,checkIn:status==="PRESENT"?now.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:false}):null})});setBusy(null);if(!r.ok){setMessage("Could not save attendance.");return;}setMessage("Attendance saved.");load()}
  const present=employees.filter(e=>["PRESENT","HALF_DAY","WORK_FROM_HOME"].includes(map.get(e.id)?.status??"")).length;
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="text-sm font-semibold text-indigo-600">Daily tracking</div><h1 className="mt-1 text-3xl font-black">Attendance</h1><p className="mt-2 text-sm text-slate-500">One record per employee per day. Change the status any time.</p></div><div className="flex items-center gap-2"><input type="date" className="input w-auto" value={date} onChange={e=>setDate(e.target.value)}/><button className="btn btn-secondary" onClick={()=>setDate(keyDate())}>Today</button></div></div>
    <div className="grid gap-4 sm:grid-cols-3"><div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">Workforce</div><div className="mt-2 text-3xl font-black">{employees.length}</div><div className="mt-1 text-xs text-slate-500">employees</div></div><div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">Marked</div><div className="mt-2 text-3xl font-black">{records.length}</div><div className="mt-1 text-xs text-slate-500">records for selected date</div></div><div className="card p-5"><div className="text-xs font-bold uppercase tracking-wide text-slate-400">Present</div><div className="mt-2 text-3xl font-black">{present}</div><div className="mt-1 text-xs text-slate-500">including WFH / half-day</div></div></div>
    <div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="font-bold">Employee attendance</h2><p className="mt-0.5 text-xs text-slate-500">Selected date: {new Date(`${date}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</p></div>{message&&<div className="text-xs font-semibold text-emerald-600">{message}</div>}</div><div className="overflow-x-auto"><table className="min-w-full text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Employee</th><th className="px-5 py-3">Department</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Check in</th><th className="px-5 py-3">Update</th></tr></thead><tbody className="divide-y divide-slate-100">{employees.map(e=>{const rec=map.get(e.id);return <tr key={e.id}><td className="px-5 py-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100 text-xs font-bold">{e.firstName[0]}{e.lastName[0]}</div><div><div className="text-sm font-bold">{e.firstName} {e.lastName}</div><div className="text-xs text-slate-500">{e.employeeCode}</div></div></div></td><td className="px-5 py-4 text-sm text-slate-600">{e.department}</td><td className="px-5 py-4"><span className={`badge ${rec?.status==="ABSENT"?"bg-rose-50 text-rose-700":rec?.status?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500"}`}>{rec?.status?.replaceAll("_"," ")??"NOT MARKED"}</span></td><td className="px-5 py-4 text-sm text-slate-500">{rec?.checkIn?<span className="inline-flex items-center gap-1"><Clock3 size={14}/>{rec.checkIn}</span>:"—"}</td><td className="px-5 py-4"><div className="flex flex-wrap gap-1.5">{statuses.map(s=><button key={s} disabled={busy===e.id} onClick={()=>save(e.id,s)} className={`rounded-lg border px-2.5 py-1.5 text-[11px] font-bold transition ${rec?.status===s?"border-indigo-200 bg-indigo-50 text-indigo-700":"border-slate-200 bg-white text-slate-500 hover:bg-slate-50"}`}>{rec?.status===s&&<Check className="mr-1 inline" size={12}/>} {s.replaceAll("_"," ")}</button>)}</div></td></tr>})}</tbody></table></div></div>
  </div>
}
